name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Added manual trigger

jobs:
  build:
    runs-on: windows-latest

    env:
      BASE_VERSION: 1.0.0

    steps:
      - uses: actions/checkout@v4

      - name: Set version variable
        shell: bash
        run: echo "VERSION=${BASE_VERSION}.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Publish self-contained WinForms app
        run: >
          dotnet publish SimpleInstallerWinForms\SimpleInstallerWinForms.csproj
          -c Release
          -r win-x64
          --self-contained true
          -o ./publish
          /p:Version=${{ env.VERSION }}

      - name: Set version in installer.iss
        shell: pwsh
        run: |
          $version = "${{ env.VERSION }}"
          (Get-Content installer.iss) -replace '^AppVersion\s*=.*', "AppVersion=$version" | Set-Content installer.iss

      - name: Build Inno Setup installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: installer.iss

      - name: Create GitHub Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: SimpleInstallerWinForms-${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: Output/SimpleInstallerWinForms-${{ env.VERSION }}.exe
          asset_name: SimpleInstallerWinForms-${{ env.VERSION }}.exe
          asset_content_type: application/octet-stream