name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      BASE_VERSION: 1.0.0

    steps:
      - uses: actions/checkout@v4

      - name: Set version variable
        shell: bash
        run: echo "VERSION=${BASE_VERSION}.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Publish self-contained WinForms app
        run: >
          dotnet publish SimpleInstallerWinForms.csproj
          -c Release
          -r win-x64
          --self-contained true
          -o ./publish
          /p:Version=${{ env.VERSION }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WinFormsApp
          path: ./publish

      - name: Install Inno Setup
        run: winget install -e --id JRSoftware.InnoSetup

      - name: Update installer version
        run: |
          (Get-Content installer.iss) -replace '^(AppVersion\s*=).*', "`$1${{ env.VERSION }}" | Set-Content installer.iss
        shell: pwsh

      - name: Build Inno Setup installer
        run: '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss'

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WinFormsInstaller
          path: installer.exe
