name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      BASE_VERSION: 1.0.0

    steps:
      - uses: actions/checkout@v4

      - name: Set version variable
        shell: bash
        run: echo "VERSION=${BASE_VERSION}.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Publish self-contained WinForms app
        run: >
          dotnet publish SimpleInstallerWinForms.csproj
          -c Release
          -r win-x64
          --self-contained true
          -o ./publish
          /p:Version=${{ env.VERSION }}
          /p:FileVersion=${{ env.VERSION }}
          /p:AssemblyVersion=${{ env.VERSION }}
          /p:InformationalVersion=${{ env.VERSION }}
          /p:NuGetVersion=${{ env.VERSION }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WinFormsApp
          path: ./publish
