name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      BASE_VERSION: 1.0.0

    steps:
      - uses: actions/checkout@v4

      - name: Set version variable
        shell: bash
        run: echo "VERSION=${BASE_VERSION}.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Publish self-contained WinForms app
        run: >
          dotnet publish SimpleInstallerWinForms.csproj
          -c Release
          -r win-x64
          --self-contained true
          -o ./publish
          /p:Version=${{ env.VERSION }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WinFormsApp
          path: ./publish

      - name: Set version in installer.iss
        shell: pwsh
        run: |
          (Get-Content installer.iss) -replace '^(AppVersion\s*=).*', "$1${{ env.VERSION }}" | Set-Content installer.iss

      - name: Build Inno Setup installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: installer.iss

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WinFormsInstaller-${{ env.VERSION }}
          path: Output/SimpleInstallerWinForms.exe

